### ISSUE TITLE
Running Executable RunFatrop.cpp

### ISSUE THREAD

**Issue by Nabil-Miri** [meco-group/fatrop#1]
When I run RunFatrop.cpp file runing vscode I get this error:
```
*  Executing task: C/C++: gcc build active file 

Starting build...
/usr/bin/gcc -fdiagnostics-color=always -g /home/nabil/fatrop/fatrop/executables/RunFatrop.cpp -o /home/nabil/fatrop/fatrop/executables/RunFatrop
/home/nabil/fatrop/fatrop/executables/RunFatrop.cpp:22:10: fatal error: fatrop/ocp/StageOCPApplication.hpp: No such file or directory
   22 | #include <fatrop/ocp/StageOCPApplication.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s).
```

Should I run anything before?

**Comment by lvanroye** [comment]
Hi Nabil, 

It seems that vscode is not able to determine the right include path. Have you considered using vscode's cmake integration? For me that works well.

Best,
Lander

**Comment by Nabil-Miri** [comment]
Dear Lander,
Thanks, it worked. I was using `C/C++: Run C/C++ File` other than` CMake: Build`.

BTW another small question. This link says there is a Fatrop interface with CasADi [https://web.casadi.org/python-api/]. Is it used differently than the spectool you created? (if yes is there any example to use it ?)

Best,
Nabil

**Comment by lvanroye** [comment]
Hi Nabil, 

@jgillis, one of the CasADi developers, tried to implement fatrop as conic solver. I am not really aware of what the current progress is on that. 

Ideally, such interface should also be developed for nonlinear optimal control problems but it is a bit challenging because  the (constrained) OCP-multiple shooting structure will have to be detected from a general NLP. It is something I'd really like to have but at this point it's a bit hard to make promises. For now, my recommendation is to use rockit or fatrop::spectool for specifying fatrop problems. 

Best,
Lander

**Comment by Nabil-Miri** [comment]
Hi Lander,

Thanks again for your reply and the detailed answer. 
Noted. So for now, I will use the fatrop::spectool.

Best,
Nabil
